package UsainSprintPages.Owner;

import Controller.Owner.CheckDateController;
import Controller.Owner.GetStatusController;
import Controller.Owner.OwnerViewController;
import Controller.Owner.generateReportController;
import UsainSprintPages.UserAdmin.LoginPage;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Orders;

public class OwnerHomePage extends javax.swing.JFrame {

    private static final int JF_W = 1353;
    private static final int JF_H = 710;

    public Dimension getPreferredSize() {
        return new Dimension(JF_W, JF_H);
    }

    public String FDateString;
    public String TDateString;

    /**
     * Creates new form OwnerHomePage
     */
    public OwnerHomePage() {
        initComponents();
        SetDate();
        show1.setVisible(false);
        show2.setVisible(false);
        show3.setVisible(false);
        show4.setVisible(false);
        generateReport();
        SetStatus();
    }

    public OwnerHomePage(String ShowName) {
        initComponents();
        SetDate();
        ShowNa.setText(ShowName);
        show1.setVisible(false);
        show2.setVisible(false);
        show3.setVisible(false);
        show4.setVisible(false);
        generateReport();
        SetStatus();
    }

    public void SetDate() {
        CheckDateController CheckD = new CheckDateController();

        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        String B = CheckD.CheckBigDate();
        String s = CheckD.CheckSmallDate();

        try {
            Date BDate = fmt.parse(B);
            Date SDate = fmt.parse(s);
            fromDate.setMaxSelectableDate(BDate);
            fromDate.setMinSelectableDate(SDate);
            fromDate.setDate(SDate);
            toDate.setMaxSelectableDate(BDate);
            toDate.setMinSelectableDate(SDate);
            toDate.setDate(BDate);
            

        } catch (ParseException ex) {
            Logger.getLogger(OwnerHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show1 = new javax.swing.JLabel();
        AvgTxt = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        TxtPhone = new javax.swing.JLabel();
        TxtHprice = new javax.swing.JLabel();
        show3 = new javax.swing.JLabel();
        MaxItem = new javax.swing.JLabel();
        Maxquantity = new javax.swing.JLabel();
        show4 = new javax.swing.JLabel();
        MinItem = new javax.swing.JLabel();
        MinQuantity = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fromDate = new com.toedter.calendar.JDateChooser();
        lblToDateText = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        SubmitBtn = new javax.swing.JButton();
        getStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ShowNa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1353, 710));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show1.setText("Average spent by all customers is");
        getContentPane().add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 240, 40));

        AvgTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(AvgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 140, 40));

        show2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show2.setText("Highest spending customer is");
        getContentPane().add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, 40));

        TxtPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 130, 40));

        TxtHprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TxtHprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 140, 40));

        show3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show3.setText("Highest number of food item purchased is");
        getContentPane().add(show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, 50));

        MaxItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(MaxItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 240, 50));

        Maxquantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Maxquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 130, 50));

        show4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show4.setText("Lowest number of food item purchased is");
        getContentPane().add(show4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, -1, 50));

        MinItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(MinItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 250, 50));

        MinQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(MinQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 130, 50));

        jPanel1.setBackground(new java.awt.Color(0, 142, 155));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromDatePropertyChange(evt);
            }
        });
        jPanel1.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 140, 30));

        lblToDateText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblToDateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToDateText.setText("—");
        lblToDateText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblToDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, 30));

        toDate.setDateFormatString("yyyy-MM-dd");
        toDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                toDatePropertyChange(evt);
            }
        });
        jPanel1.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 140, 30));

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, 30));

        jPanel1.add(getStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1170, 100));

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPhone", "Date", "ToTal", "Discount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ReportTable);
        if (ReportTable.getColumnModel().getColumnCount() > 0) {
            ReportTable.getColumnModel().getColumn(0).setResizable(false);
            ReportTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 1160, 370));

        jPanel2.setBackground(new java.awt.Color(0, 31, 125));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowNa.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        ShowNa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ShowNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hello");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 10));

        jLabel19.setFont(new java.awt.Font("Academy Engraved LET", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usain Sprint");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 70));

        logout.setBackground(new java.awt.Color(0, 31, 125));
        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SetStatus()
    {
        Iterator<Orders> itr = GetStatusController.getStatus();
        while(itr.hasNext())
        {
            Orders or = itr.next();
            getStatus.addItem(or.getStatus());
        }
    }
    
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void toDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_toDatePropertyChange
        fromDate.setMaxSelectableDate(toDate.getDate());
        SubmitBtn.setEnabled(true);
    }//GEN-LAST:event_toDatePropertyChange

    private void generateReport() {
        DateFormat Df = new SimpleDateFormat("yyyy-MM-dd");
        String gStatus =(String)getStatus.getSelectedItem();
        generateReportController Grp = new generateReportController();
        Grp.fromDate = Df.format(fromDate.getDate());
        Grp.toDate = Df.format(toDate.getDate());
        Grp.Status = gStatus;
        FDateString = Df.format(fromDate.getDate());
        TDateString = Df.format(toDate.getDate());
        AvgTxt.setText(String.valueOf(Grp.AveData()));
        Orders Or = Grp.HighP();
        TxtPhone.setText(Or.getPhone());
        TxtHprice.setText(String.valueOf(Or.getHightPrice()));
        MaxItem.setText(Or.getMaxItemName());
        Maxquantity.setText(String.valueOf(Or.getMaxQuantity()));
        MinItem.setText(Or.getMinItemName());
        MinQuantity.setText(String.valueOf(Or.getLowerQuantity()));
        
        DefaultTableModel dtm = (DefaultTableModel) ReportTable.getModel();
        dtm.setRowCount(0);

        Iterator<Orders> itrIt = OwnerViewController.ViewTable(FDateString, TDateString,gStatus);
        while (itrIt.hasNext()) {
            Orders oObj = itrIt.next();
            dtm.addRow(new Object[]{oObj.getId(), oObj.getPhone(), oObj.getDate(), oObj.getTotal(), oObj.getDiscount(), oObj.getStatus()});
        }
        show1.setVisible(true);
        show2.setVisible(true);
        show3.setVisible(true);
        show4.setVisible(true);
    }

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        generateReport();
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
//        DefaultTableModel dtm = (DefaultTableModel) ReportTable.getModel();
//        JOptionPane.showMessageDialog(null, FDateString);
//        JOptionPane.showMessageDialog(null, TDateString);
//        Iterator<Orders> itrIt= OwnerViewController.ViewTable(FDateString, TDateString);
//        while(itrIt.hasNext())
//        {
//            Orders oObj= itrIt.next();
//            dtm.addRow(new Object[]{oObj.getId(),oObj.getPhone(),oObj.getDate(),oObj.getTotal(),oObj.getDiscount(),oObj.getStatus()});
//        }
    }//GEN-LAST:event_formComponentShown

    private void fromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromDatePropertyChange
        toDate.setMinSelectableDate(fromDate.getDate());
        SubmitBtn.setEnabled(true);
    }//GEN-LAST:event_fromDatePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvgTxt;
    private javax.swing.JLabel MaxItem;
    private javax.swing.JLabel Maxquantity;
    private javax.swing.JLabel MinItem;
    private javax.swing.JLabel MinQuantity;
    private javax.swing.JTable ReportTable;
    private javax.swing.JLabel ShowNa;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TxtHprice;
    private javax.swing.JLabel TxtPhone;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JComboBox<String> getStatus;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblToDateText;
    private javax.swing.JButton logout;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel show2;
    private javax.swing.JLabel show3;
    private javax.swing.JLabel show4;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
